project:
  type: website

execute:
  freeze: auto

website:
  title: "Alexandra AI Leaderboard"
  search: false
  repo-url: https://github.com/alexandrainst/AlexandraAI-eval
  repo-actions: [edit, issue]
  sidebar:
    logo: logo.png
    style: "docked"
    contents: 
      - auto: boards/*.qmd
      - about.qmd
  page-footer: "Copyright 2023, Alexandra Instituttet"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false